# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: DNS-Proxy_setup
# label used for menu selection
label: DNS-Proxy configuration skillet
description: provisions NGFW DNS-Proxy

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - DNS-proxy setup

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: dns_proxy_name
    description: DNS Proxy name:
    default: dns_proxy
    type_hint: text
  - name: enable_ttl
      description: Enable TTL?
      default: no
      type_hint: dropdown
      dd_list:
        - key: yes
          value: yes
        - key: no
          value: no
  - name: primary_dns
      description: Enter the hostname or IP address of the primary DNS server:
      default: 1.1.1.1
      type_hint: ip_address
  - name: secondary_dns
      description: Enter the hostname or IP address of the secondary DNS server:
      default: 8.8.8.8
      type_hint: ip_address
  - name: tcp_queries
      description: Enable TCP queries?
      default: no
      type_hint: dropdown
      dd_list:
        - key: yes
          value: yes
        - key: no
          value: no
  - name: proxy_interface
      description: Add an interface to function as a DNS proxy
      default: ethernet1/1
      type_hint: dropdown
      dd_list:
        - key: tag_member
          value: ethernet1/1
        - key: tunnel
          value: tunnel
        - key: vlan
          value: vlan
        - key: loopback
          value: loopback
  - name: rule_name
    description: DNS Proxy rule name:
    default: rule_1
    type_hint: text
  - name: domain_a
    description: Proxied domain name:
    default: a@local
    type_hint: text
  - name: domain_b
    description: Proxied domain name:
    default: b@local
    type_hint: text
  - name: domain_c
    description: Proxied domain name:
    default: c@local
    type_hint: text
  - name: domain_d
    description: Proxied domain name:
    default: d@local
    type_hint: text
  - name: domain_e
    description: Proxied domain name:
    default: e@local
    type_hint: text
  - name: primary
    description: Primary DNS
    default: 1.1.1.1
    type_hint: ip_address
  - name: secondary
    description: Secondary DNS:
    default: 8.8.8.8
    type_hint: ip_address
  - name: cache_domain
      description: Enable caching of domains?
      default: yes
      type_hint: dropdown
      dd_list:
        - key: yes
          value: yes
        - key: no
          value: no
   - name: static_nameserver
      description: Enter a name for the static entry:
      default: foobar.local
      type_hint: text
   - name: nameserver_ip
      description: Enter IP address:
      default: 1.1.1.1
      type_hint: ip_address
   - name: domain_name
      description: Enter FQDN:
      default: foobar.local
      type_hint: text


# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: dns-proxy
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/dns-proxy


# ---------------------------------------------------------------------
# end of snippets section
